version: '3'
services:
  top.api:
    image: ghcr.io/igerne94/top-api/top-api:develop
    container_name: top-api
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./.env:/opt/app/.env
