version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data-4.4:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    networks:
      - app-network

  top.api:
    platform: linux/arm64
    build: .
    image: ghcr.io/igerne94/top-api/top-api:develop
    container_name: top-api
    depends_on:
      - mongo
    restart: always
    ports:
      - 3030:3000
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/top_api?authSource=admin
    volumes:
      - ./.env:/opt/app/.env
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
