name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish Docker container
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/igerne94/top-api/top-api
          username: ${{ secrets.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: "develop"